apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hello-gateway
  namespace: kubecon-demo
spec:
  selector:
    istio: ingressgateway # use istio default gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "hello.local"

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-dest
  namespace: kubecon-demo
spec:
  host: hello
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
