---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello
  namespace: kubecon-demo
spec:
  gateways:
    - "hello-gateway"
  hosts:
    - "hello.local"
  http:
    - route:
        - destination:
            host: hello
            subset: v1